2022-12-01 21:27:47,200 — ERROR : Please enter a numerical value for the refugee ID.
Traceback (most recent call last):
  File "/Users/beautiez/Documents/emergency-system/core_code/refugee_validation.py", line 125, in refugee_validity_check_by_ID
    ref_id = int(input(f"Please input refugee ID of whom you wish to {cond} the information: "))
ValueError: invalid literal for int() with base 10: 'Rena'
2022-12-01 22:02:52,073 — ERROR : Please enter a numerical value for the refugee ID.
Traceback (most recent call last):
  File "/Users/beautiez/Documents/emergency-system/core_code/refugee_validation.py", line 128, in refugee_validity_check_by_ID
    df_ref_search = pd.DataFrame(data = refugee_list,columns=["refugeeID","campID","fName","lName","birthdate","gender","ethnicGroup","email",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 760, in __init__
    mgr = ndarray_to_mgr(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 349, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (2, 1), indices imply (2, 16)
2022-12-01 22:03:05,335 — ERROR : Please enter a numerical value for the refugee ID.
Traceback (most recent call last):
  File "/Users/beautiez/Documents/emergency-system/core_code/refugee_validation.py", line 128, in refugee_validity_check_by_ID
    df_ref_search = pd.DataFrame(data = refugee_list,columns=["refugeeID","campID","fName","lName","birthdate","gender","ethnicGroup","email",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/frame.py", line 760, in __init__
    mgr = ndarray_to_mgr(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 349, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (2, 1), indices imply (2, 16)
2022-12-01 22:11:00,689 — ERROR : Please enter a numerical value for the refugee ID.
Traceback (most recent call last):
  File "/Users/beautiez/Documents/emergency-system/core_code/refugee_validation.py", line 124, in refugee_validity_check_by_ID
    opt = col_opt[int(input('Please select how you want to search: '))]
ValueError: invalid literal for int() with base 10: 're'
2022-12-01 22:14:19,197 — ERROR : Your input is invalid in our database
Traceback (most recent call last):
  File "/Users/beautiez/Documents/emergency-system/core_code/refugee_validation.py", line 130, in refugee_validity_check_by_ID
    raise exp.refugee_id_out_of_range
refugee_exception.refugee_id_out_of_range
2022-12-01 22:14:52,551 — ERROR : Your input is invalid in our database
Traceback (most recent call last):
  File "/Users/beautiez/Documents/emergency-system/core_code/refugee_validation.py", line 129, in refugee_validity_check_by_ID
    raise exp.refugee_id_out_of_range
refugee_exception.refugee_id_out_of_range
